//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoClient.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        string GetData(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        CryptoServer.CompositeType GetDataUsingDataContract(CryptoServer.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<CryptoServer.CompositeType> GetDataUsingDataContractAsync(CryptoServer.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AesEncrypt", ReplyAction="http://tempuri.org/IService/AesEncryptResponse")]
        void AesEncrypt(CryptoServer.Helper.FileExtend[] list, byte[] key, byte[] IV, string rootFolder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AesEncrypt", ReplyAction="http://tempuri.org/IService/AesEncryptResponse")]
        System.Threading.Tasks.Task AesEncryptAsync(CryptoServer.Helper.FileExtend[] list, byte[] key, byte[] IV, string rootFolder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AesDecrypt", ReplyAction="http://tempuri.org/IService/AesDecryptResponse")]
        void AesDecrypt(CryptoServer.Helper.FileExtend[] list, byte[] key, byte[] IV, string rootFolder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AesDecrypt", ReplyAction="http://tempuri.org/IService/AesDecryptResponse")]
        System.Threading.Tasks.Task AesDecryptAsync(CryptoServer.Helper.FileExtend[] list, byte[] key, byte[] IV, string rootFolder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/XXTEAEncrypt", ReplyAction="http://tempuri.org/IService/XXTEAEncryptResponse")]
        void XXTEAEncrypt(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/XXTEAEncrypt", ReplyAction="http://tempuri.org/IService/XXTEAEncryptResponse")]
        System.Threading.Tasks.Task XXTEAEncryptAsync(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/XXTEADecrypt", ReplyAction="http://tempuri.org/IService/XXTEADecryptResponse")]
        void XXTEADecrypt(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/XXTEADecrypt", ReplyAction="http://tempuri.org/IService/XXTEADecryptResponse")]
        System.Threading.Tasks.Task XXTEADecryptAsync(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RC6Encrypt", ReplyAction="http://tempuri.org/IService/RC6EncryptResponse")]
        void RC6Encrypt(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RC6Encrypt", ReplyAction="http://tempuri.org/IService/RC6EncryptResponse")]
        System.Threading.Tasks.Task RC6EncryptAsync(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RC6Decrypt", ReplyAction="http://tempuri.org/IService/RC6DecryptResponse")]
        void RC6Decrypt(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RC6Decrypt", ReplyAction="http://tempuri.org/IService/RC6DecryptResponse")]
        System.Threading.Tasks.Task RC6DecryptAsync(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AesEncryptP", ReplyAction="http://tempuri.org/IService/AesEncryptPResponse")]
        void AesEncryptP(CryptoServer.Helper.FileExtend[] list, byte[] key, byte[] IV, string rootFolder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AesEncryptP", ReplyAction="http://tempuri.org/IService/AesEncryptPResponse")]
        System.Threading.Tasks.Task AesEncryptPAsync(CryptoServer.Helper.FileExtend[] list, byte[] key, byte[] IV, string rootFolder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AesDecryptP", ReplyAction="http://tempuri.org/IService/AesDecryptPResponse")]
        void AesDecryptP(CryptoServer.Helper.FileExtend[] list, byte[] key, byte[] IV, string rootFolder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AesDecryptP", ReplyAction="http://tempuri.org/IService/AesDecryptPResponse")]
        System.Threading.Tasks.Task AesDecryptPAsync(CryptoServer.Helper.FileExtend[] list, byte[] key, byte[] IV, string rootFolder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/XXTEAEncryptP", ReplyAction="http://tempuri.org/IService/XXTEAEncryptPResponse")]
        void XXTEAEncryptP(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/XXTEAEncryptP", ReplyAction="http://tempuri.org/IService/XXTEAEncryptPResponse")]
        System.Threading.Tasks.Task XXTEAEncryptPAsync(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/XXTEADecryptP", ReplyAction="http://tempuri.org/IService/XXTEADecryptPResponse")]
        void XXTEADecryptP(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/XXTEADecryptP", ReplyAction="http://tempuri.org/IService/XXTEADecryptPResponse")]
        System.Threading.Tasks.Task XXTEADecryptPAsync(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RC6EncryptP", ReplyAction="http://tempuri.org/IService/RC6EncryptPResponse")]
        void RC6EncryptP(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RC6EncryptP", ReplyAction="http://tempuri.org/IService/RC6EncryptPResponse")]
        System.Threading.Tasks.Task RC6EncryptPAsync(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RC6DecryptP", ReplyAction="http://tempuri.org/IService/RC6DecryptPResponse")]
        void RC6DecryptP(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RC6DecryptP", ReplyAction="http://tempuri.org/IService/RC6DecryptPResponse")]
        System.Threading.Tasks.Task RC6DecryptPAsync(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : CryptoClient.ServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<CryptoClient.ServiceReference.IService>, CryptoClient.ServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(string value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(string value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public CryptoServer.CompositeType GetDataUsingDataContract(CryptoServer.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<CryptoServer.CompositeType> GetDataUsingDataContractAsync(CryptoServer.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public void AesEncrypt(CryptoServer.Helper.FileExtend[] list, byte[] key, byte[] IV, string rootFolder) {
            base.Channel.AesEncrypt(list, key, IV, rootFolder);
        }
        
        public System.Threading.Tasks.Task AesEncryptAsync(CryptoServer.Helper.FileExtend[] list, byte[] key, byte[] IV, string rootFolder) {
            return base.Channel.AesEncryptAsync(list, key, IV, rootFolder);
        }
        
        public void AesDecrypt(CryptoServer.Helper.FileExtend[] list, byte[] key, byte[] IV, string rootFolder) {
            base.Channel.AesDecrypt(list, key, IV, rootFolder);
        }
        
        public System.Threading.Tasks.Task AesDecryptAsync(CryptoServer.Helper.FileExtend[] list, byte[] key, byte[] IV, string rootFolder) {
            return base.Channel.AesDecryptAsync(list, key, IV, rootFolder);
        }
        
        public void XXTEAEncrypt(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder) {
            base.Channel.XXTEAEncrypt(list, key, rootFolder);
        }
        
        public System.Threading.Tasks.Task XXTEAEncryptAsync(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder) {
            return base.Channel.XXTEAEncryptAsync(list, key, rootFolder);
        }
        
        public void XXTEADecrypt(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder) {
            base.Channel.XXTEADecrypt(list, key, rootFolder);
        }
        
        public System.Threading.Tasks.Task XXTEADecryptAsync(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder) {
            return base.Channel.XXTEADecryptAsync(list, key, rootFolder);
        }
        
        public void RC6Encrypt(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder) {
            base.Channel.RC6Encrypt(list, key, rootFolder);
        }
        
        public System.Threading.Tasks.Task RC6EncryptAsync(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder) {
            return base.Channel.RC6EncryptAsync(list, key, rootFolder);
        }
        
        public void RC6Decrypt(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder) {
            base.Channel.RC6Decrypt(list, key, rootFolder);
        }
        
        public System.Threading.Tasks.Task RC6DecryptAsync(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder) {
            return base.Channel.RC6DecryptAsync(list, key, rootFolder);
        }
        
        public void AesEncryptP(CryptoServer.Helper.FileExtend[] list, byte[] key, byte[] IV, string rootFolder) {
            base.Channel.AesEncryptP(list, key, IV, rootFolder);
        }
        
        public System.Threading.Tasks.Task AesEncryptPAsync(CryptoServer.Helper.FileExtend[] list, byte[] key, byte[] IV, string rootFolder) {
            return base.Channel.AesEncryptPAsync(list, key, IV, rootFolder);
        }
        
        public void AesDecryptP(CryptoServer.Helper.FileExtend[] list, byte[] key, byte[] IV, string rootFolder) {
            base.Channel.AesDecryptP(list, key, IV, rootFolder);
        }
        
        public System.Threading.Tasks.Task AesDecryptPAsync(CryptoServer.Helper.FileExtend[] list, byte[] key, byte[] IV, string rootFolder) {
            return base.Channel.AesDecryptPAsync(list, key, IV, rootFolder);
        }
        
        public void XXTEAEncryptP(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder) {
            base.Channel.XXTEAEncryptP(list, key, rootFolder);
        }
        
        public System.Threading.Tasks.Task XXTEAEncryptPAsync(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder) {
            return base.Channel.XXTEAEncryptPAsync(list, key, rootFolder);
        }
        
        public void XXTEADecryptP(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder) {
            base.Channel.XXTEADecryptP(list, key, rootFolder);
        }
        
        public System.Threading.Tasks.Task XXTEADecryptPAsync(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder) {
            return base.Channel.XXTEADecryptPAsync(list, key, rootFolder);
        }
        
        public void RC6EncryptP(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder) {
            base.Channel.RC6EncryptP(list, key, rootFolder);
        }
        
        public System.Threading.Tasks.Task RC6EncryptPAsync(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder) {
            return base.Channel.RC6EncryptPAsync(list, key, rootFolder);
        }
        
        public void RC6DecryptP(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder) {
            base.Channel.RC6DecryptP(list, key, rootFolder);
        }
        
        public System.Threading.Tasks.Task RC6DecryptPAsync(CryptoServer.Helper.FileExtend[] list, byte[] key, string rootFolder) {
            return base.Channel.RC6DecryptPAsync(list, key, rootFolder);
        }
    }
}
